name: Deploy Spring Boot to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-docker.pkg.dev

      - name: Build & Push Docker image
        run: |
          docker build -t asia-docker.pkg.dev/celestial-air-455806-v8/library-repo-01/spring-app:$GITHUB_SHA .
          docker push asia-docker.pkg.dev/celestial-air-455806-v8/library-repo-01/spring-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy jiu-app \
            --image=asia-docker.pkg.dev/celestial-air-455806-v8/library-repo-01/spring-app:$GITHUB_SHA \
            --platform=managed \
            --region=asia-northeast1 \
            --allow-unauthenticated \
            --add-cloudsql-instances=celestial-air-455806-v8:asia-northeast1:mysql01 \
            --set-env-vars=DB_USER=root,DB_PASS=0000,DB_NAME=library,INSTANCE_CONNECTION_NAME=celestial-air-455806:asia-northeast1:mysql01
